@startuml

title 时序图

== 鉴权阶段 ==

Alice -> Bob: 请求
Bob -> Alice: 应答

== 数据上传 ==

Alice -> Bob: 上传数据
note left: 这是显示在左边的备注

Bob --> Canny: 转交数据
... 不超过 5 秒钟 ...
Canny --> Bob: 状态返回
note right: 这是显示在右边的备注

Bob -> Alice: 状态返回

== 状态显示 ==

Alice -> Alice: 给自己发消息

@enduml

TIPS：



使用 title 来指定标题
'->' 和 '-->' 来指示线条的形式
在每个时序后面加冒号 : 来添加注释
使用 note 来显示备注，备注可以指定显示在左边或右边
使用 == xxx == 来分隔时序图
使用 ... 来表示延迟省略号
节点可以给自己发送消息，方法是发送方和接收方使用同一个主体即可

作者：kamidox
链接：http://www.jianshu.com/p/e92a52770832
來源：简书
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。